# Generated by Django 5.2.8 on 2026-01-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(to='users.User', on_delete=models.CASCADE, related_name='tasks'),
        ),
    ]
