# Generated by Django 5.2.8 on 2026-01-10 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20260110_0348'),
    ]

    operations = [
        # Recreate the user foreign key field properly
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(to='users.User', on_delete=django.db.models.deletion.CASCADE, related_name='tasks'),
        ),
    ]
