# Generated by Django 5.2.8 on 2026-01-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_fix_user_foreign_key'),
    ]

    operations = [
        # First, remove the current user field
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        # Then add the correct user field with proper foreign key
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(
                to='users.User',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks'
            ),
        ),
    ]
